[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Material You-like colors (we can refine these)
primaryColor=#f2eadd
accentColor=#c7c9a7
backgroundColor=#1A1C18
textColor=#f2eadd

# Font settings
fontFamily=Google Sans Flex Freeze
fontSize=12
