pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    property var outputs: ({})
    property var savedConfig: ({})
    property bool ready: false
    property var _ipcDone: null

    readonly property string kdlPath: Quickshell.env("HOME") + "/ivyos/ivyshell/.config/niri/monitors.kdl"

    // ── Merge live niri state with saved kdl config ─────────────────
    function mergedOutputs() {
    const result = {}
    for (const key of Object.keys(outputs)) {
        const live = outputs[key]
        const saved = savedConfig[key] ?? {}

        result[key] = {
            name: key,
            modes: live.modes ?? [],
            current_mode: live.current_mode ?? 0,
            vrr_supported: live.vrr_supported ?? false,
            vrr_enabled: live.vrr_enabled ?? false,
            logical: {
                x:         live.logical?.x         ?? 0,
                y:         live.logical?.y          ?? 0,
                scale:     live.logical?.scale      ?? 1.0,
                transform: live.logical?.transform  ?? "Normal",
                width:     live.logical?.width      ?? 1920,
                height:    live.logical?.height     ?? 1080,
            },
            saved_mode: saved.modes?.[0] ?? null,
        }
    }
    return result
}

    // ── Parse monitors.kdl ──────────────────────────────────────────
    function parseKdl(content) {
        const result = {}
        const outputRegex = /output\s+"([^"]+)"\s*\{([^}]*)\}/g
        let match
        while ((match = outputRegex.exec(content)) !== null) {
            const name = match[1]
            const body = match[2]
            const modeMatch  = body.match(/mode\s+"(\d+)x(\d+)@([\d.]+)"/)
            const posMatch   = body.match(/position\s+x=(-?\d+)\s+y=(-?\d+)/)
            const scaleMatch = body.match(/scale\s+([\d.]+)/)
            const transMatch = body.match(/transform\s+"([^"]+)"/)
            const vrrMatch   = body.match(/variable-refresh-rate/)
            result[name] = {
                logical: {
                    x:         posMatch   ? parseInt(posMatch[1])     : 0,
                    y:         posMatch   ? parseInt(posMatch[2])     : 0,
                    scale:     scaleMatch ? parseFloat(scaleMatch[1]) : 1.0,
                    transform: transMatch ? transMatch[1]             : "Normal",
                },
                modes: modeMatch ? [{
                    width:        parseInt(modeMatch[1]),
                    height:       parseInt(modeMatch[2]),
                    refresh_rate: Math.round(parseFloat(modeMatch[3]) * 1000)
                }] : [],
                current_mode: 0,
                vrr_enabled: !!vrrMatch,
            }
        }
        return result
    }

    // ── Generate KDL ────────────────────────────────────────────────
    function generateKdl(outputsData) {
        const transformMap = {
            "Normal":     "normal",
            "90":         "90",
            "180":        "180",
            "270":        "270",
            "Flipped":    "flipped",
            "Flipped90":  "flipped-90",
            "Flipped180": "flipped-180",
            "Flipped270": "flipped-270",
        }
        let kdl = "// Auto-generated by IvyShell - do not edit manually\n\n"
        for (const key of Object.keys(outputsData)) {
            const o = outputsData[key]
            const mode = o.modes?.[o.current_mode]
            const transform = o.logical?.transform ?? "Normal"
            kdl += `output "${key}" {\n`
            if (mode)
                kdl += `    mode "${mode.width}x${mode.height}@${(mode.refresh_rate / 1000).toFixed(3)}"\n`
            kdl += `    scale ${o.logical?.scale ?? 1.0}\n`
            if (transform !== "Normal")
                kdl += `    transform "${transformMap[transform] ?? "normal"}"\n`
            kdl += `    position x=${o.logical?.x ?? 0} y=${o.logical?.y ?? 0}\n`
            if (o.vrr_enabled)
                kdl += `    variable-refresh-rate\n`
            kdl += `}\n\n`
        }
        return kdl
    }

    // ── Apply via IPC ───────────────────────────────────────────────
    function applyOutputIpc(outputName, config, onDone) {
        const cmds = []
        if (config.position !== undefined)
            cmds.push(`niri msg output "${outputName}" position ${config.position.x} ${config.position.y}`)
        if (config.mode !== undefined)
            cmds.push(`niri msg output "${outputName}" mode ${config.mode}`)
        if (config.scale !== undefined)
            cmds.push(`niri msg output "${outputName}" scale ${config.scale}`)
        if (config.transform !== undefined)
            cmds.push(`niri msg output "${outputName}" transform "${config.transform}"`)
        if (config.vrr !== undefined)
            cmds.push(`niri msg output "${outputName}" vrr ${config.vrr ? "on" : "off"}`)
        if (cmds.length === 0) {
            if (onDone) onDone(true)
            return
        }
        root._ipcDone = onDone
        ipcProc.command = ["sh", "-c", cmds.join(" && ")]
        ipcProc.running = false
        ipcProc.running = true
    }

    function refresh() {
        liveProc.running = false
        liveProc.running = true
    }

    function reloadKdl() {
        kdlFile.reload()
    }

    // ── Live fetch ──────────────────────────────────────────────────
    Process {
        id: liveProc
        command: ["niri", "msg", "--json", "outputs"]
        running: true
        stdout: SplitParser {
            onRead: data => {
                try {
                    root.outputs = JSON.parse(data)
                    root.ready = true
                } catch (e) {
                    console.warn("NiriOutputs: parse error", e)
                }
            }
        }
    }

    // ── IPC apply ───────────────────────────────────────────────────
    Process {
        id: ipcProc
        running: false
        onExited: (code) => {
            if (root._ipcDone) root._ipcDone(code === 0)
            root._ipcDone = null
            root.refresh()
        }
    }

    // ── KDL file ────────────────────────────────────────────────────
    FileView {
        id: kdlFile
        path: root.kdlPath
        blockLoading: true
        watchChanges: true
        onFileChanged: reload()
        onLoaded: root.savedConfig = root.parseKdl(kdlFile.text())
        onLoadFailed: console.warn("NiriOutputs: could not read monitors.kdl")
        Component.onCompleted: reload()
    }
}