color0 #13140d
color1 #b86161
color2 #add0a2
color3 #c7c9a7
color4 #cad193
color5 #add0a2
color6 #c7c9a7
color7 #e5e3d6
color8 #929283
color9 #b86161
color10 #add0a2
color11 #c7c9a7
color12 #cad193
color13 #add0a2
color14 #c7c9a7
color15 #e5e3d6

cursor                #c8c7b7
cursor_text_color     #191a17
background            #161615 
foreground            #f2eadd
selection_foreground  #c8c7b7
selection_background  #47483b
url_color             #cad193