[manager]
ratio = [1, 2, 3]
sort-by = "natural"
sort-sensitive = false
sort-reverse = false
sort-dir-first = true
show-hidden = true
show-symlink = true

[preview]
tab-size = 4
max-width = 1000
max-height = 1000
ueberzug-scale = 1
ueberzug-offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = 'hx "$@"', block = true, desc = "Edit" }
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" }
]

[open]
prepend_rules = [
  { name = "*.{rs,nix,toml,txt,md,json,conf,sh}", use = "edit" },
  { mime = "inode/x-empty",       use = "edit" },
  { mime = "application/x-empty", use = "edit" },
  { mime = "application/x-zerosize", use = "edit" },

  { mime = "text/*", use = "edit" },
]

rules = [
  { mime = "image/*",       use = "open" },
  { mime = "video/*",       use = "open" },
  { mime = "application/pdf", use = "open" },
  { name = "*",             use = "open" },
]
