[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }
cargo = { allFeatures = true }
procMacro = { enable = true }
inlayHints = { bindingModeHints = { enable = true }, closureCaptureHints = { enable = true } }
